
Exception caught at 2021-11-06 21:33:54.032194:
Traceback (most recent call last):
  File "internal/testpy/test_framework.py", line 238, in <module>
    main()
  File "internal/testpy/test_framework.py", line 34, in main
    input("Press Enter to Exit...")
EOFError

Exception caught at 2021-11-06 21:34:23.466588:
Traceback (most recent call last):
  File "internal/testpy/test_framework.py", line 238, in <module>
    main()
  File "internal/testpy/test_framework.py", line 34, in main
    input("Press Enter to Exit...")
EOFError

Exception caught at 2021-11-06 22:04:45.153263:
Traceback (most recent call last):
  File "internal/testpy/test_framework.py", line 238, in <module>
    main()
  File "internal/testpy/test_framework.py", line 34, in main
    input("Press Enter to Exit...")
EOFError

Exception caught at 2021-11-06 22:05:41.331525:
Traceback (most recent call last):
  File "internal/testpy/test_framework.py", line 238, in <module>
    main()
  File "internal/testpy/test_framework.py", line 34, in main
    input("Press Enter to Exit...")
EOFError

Exception caught at 2021-11-06 22:45:44.073944:
Traceback (most recent call last):
  File "internal/testpy/test_framework.py", line 238, in <module>
    main()
  File "internal/testpy/test_framework.py", line 57, in main
    input("Press Enter To Exit...")
EOFError: EOF when reading a line

Exception caught at 2021-11-07 00:29:14.995504:
Traceback (most recent call last):
  File "internal/testpy/test_framework.py", line 238, in <module>
    main()
  File "internal/testpy/test_framework.py", line 57, in main
    input("Press Enter To Exit...")
EOFError: EOF when reading a line

Exception caught at 2021-11-07 01:41:03.778450:
Traceback (most recent call last):
  File "internal/testpy/test_framework.py", line 238, in <module>
    main()
  File "internal/testpy/test_framework.py", line 57, in main
    input("Press Enter To Exit...")
EOFError

Exception caught at 2021-11-07 01:41:11.557953:
Traceback (most recent call last):
  File "internal/testpy/test_framework.py", line 238, in <module>
    main()
  File "internal/testpy/test_framework.py", line 57, in main
    input("Press Enter To Exit...")
EOFError: EOF when reading a line

Exception caught at 2021-11-07 15:44:06.543819:
Traceback (most recent call last):
  File "internal/testpy/test_framework.py", line 238, in <module>
    main()
  File "internal/testpy/test_framework.py", line 57, in main
    input("Press Enter To Exit...")
EOFError

Exception caught at 2021-11-07 15:44:38.672086:
Traceback (most recent call last):
  File "internal/testpy/test_framework.py", line 238, in <module>
    main()
  File "internal/testpy/test_framework.py", line 57, in main
    input("Press Enter To Exit...")
EOFError

Exception caught at 2021-11-07 15:47:06.771945:
Traceback (most recent call last):
  File "internal/testpy/test_framework.py", line 238, in <module>
    main()
  File "internal/testpy/test_framework.py", line 57, in main
    input("Press Enter To Exit...")
EOFError

Exception caught at 2021-11-07 17:29:37.725258:
Traceback (most recent call last):
  File "internal/testpy/test_framework.py", line 238, in <module>
    main()
  File "internal/testpy/test_framework.py", line 57, in main
    input("Press Enter To Exit...")
EOFError

Exception caught at 2021-11-07 20:11:36.772314:
Traceback (most recent call last):
  File "internal/testpy/test_framework.py", line 238, in <module>
    main()
  File "internal/testpy/test_framework.py", line 57, in main
    input("Press Enter To Exit...")
EOFError: EOF when reading a line
